### ISSUE TITLE
stuck in yarn install

### ISSUE THREAD

**Issue by MohdNasir997** [fxmarty/rikai-mpv#11]
this is the error , I am receiving:
yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

**Comment by fxmarty** [comment]
@MohdNasir997 Did you manage to make it work? Cheers!

**Comment by MohdNasir997** [comment]
It works but subtitles are now not visible,  but when I stop rikai,
subtitles appear again.

**Comment by fxmarty** [comment]
@MohdNasir997 Ok that's bad. Are you on Linux? Are all the dependencies installed? Could you launch mpv from the command line and tell me what the logs are?

**Comment by MohdNasir997** [comment]
yes, mine is zorin OS , which is a ubuntu distro, here is the relevant
terminal information,
(+) Video --vid=1 (*) (h264 1280x720 23.975fps)
 (+) Audio --aid=1 --alang=jpn (*) (aac 2ch 48000Hz)
Using hardware decoding (vaapi).
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1280x720 vaapi[nv12]
AV: 00:00:01 / 00:32:30 (0%) A-V:  0.000
[osd/libass] fontselect: Using default font family: (mpv-osd-symbols, 400,
0) -> /usr/share/fonts/truetype/croscore/Arimo-Regular.ttf, 0, Arimo
(Paused) AV: 00:00:05 / 00:32:30 (0%) A-V: -0.000 Dropped: 1
Track added:
 (+) Video --vid=1 (*) (h264 1280x720 23.975fps)
 (+) Audio --aid=1 --alang=jpn (*) (aac 2ch 48000Hz)
 (+) Subs  --sid=1
'ReZERO%20-Starting%20Life%20in%20Another%20World-%20Director's%20Cut.S02E04.CC.ja.srt'
(subrip) (external)
(Paused) AV: 00:00:07 / 00:32:30 (0%) A-V:  0.000 Dropped: 2
[front] Starting rikai-mpv...
[rikai-mpv] Starting rikai-mpv in python...opped: 2
Launching node.js backend...
Connecting from Python...
/home/nasir/.config/mpv/scripts/rikai-mpv/rikaichamp-backend/extension/background_search_html.js:37
import { WordsDictionary } from './data_words.js';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
AV: 00:00:23 / 00:32:30 (1%) A-V:  0.000 Dropped: 4
[front] Quitting rikai-mpv...
AV: 00:00:23 / 00:32:30 (1%) A-V:  0.000 Dropped: 4
[front] Finished exiting.
(Paused) AV: 00:00:24 / 00:32:30 (1%) A-V:  0.000 Dropped: 4
, hope this is helps.
