### ISSUE TITLE
subtiles are not visibel

### ISSUE THREAD

**Issue by MohdNasir997** [fxmarty/rikai-mpv#12]
[front] Starting rikai-mpv... 
[rikai-mpv] Starting rikai-mpv in python... 0.000
Launching node.js backend...
Connecting from Python...
/home/nasir/.config/mpv/scripts/rikai-mpv/rikaichamp-backend/extension/background_search_html.js:37
import { WordsDictionary } from './data_words.js';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
AV: 00:00:53 / 00:32:30 (2%) A-V:  0.000 Dropped: 2
[front] Quitting rikai-mpv... 
AV: 00:00:53 / 00:32:30 (2%) A-V:  0.000 Dropped: 2
[front] Finished exiting. 
(Paused) AV: 00:00:57 / 00:32:30 (2%) A-V:  0.000 Dropped: 2

this is what the terminal output is.

**Comment by fxmarty** [comment]
That's weird. All the steps in https://github.com/fxmarty/rikai-mpv#install are fine?

What is your node version (`node --version`)?

Could you try the following: https://github.com/fxmarty/rikai-mpv/issues/3#issuecomment-887492831

**Comment by MohdNasir997** [comment]
node -v
v18.12.1
npm -v
8.19.2
these are my version

**Comment by MohdNasir997** [comment]
here is some other outputs ,
~/.config/mpv/scripts/rikai-mpv/rikaichamp-backend$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.13s.

**Comment by MohdNasir997** [comment]
redid everything , same problem 
~/.config/mpv/scripts$ sudo rm -r rikai-mpv/
nasir@nasir-Inspiron-15-3567:~/.config/mpv/scripts$ cd ~/.config/mpv/scripts/
nasir@nasir-Inspiron-15-3567:~/.config/mpv/scripts$ git clone https://github.com/fxmarty/rikai-mpv.git
Cloning into 'rikai-mpv'...
remote: Enumerating objects: 254, done.
remote: Counting objects: 100% (254/254), done.
remote: Compressing objects: 100% (223/223), done.
remote: Total 254 (delta 92), reused 149 (delta 27), pack-reused 0
Receiving objects: 100% (254/254), 28.76 MiB | 2.24 MiB/s, done.
Resolving deltas: 100% (92/92), done.
nasir@nasir-Inspiron-15-3567:~/.config/mpv/scripts$ ln -s rikai-mpv/front.lua .
nasir@nasir-Inspiron-15-3567:~/.config/mpv/scripts$ cd rikai-mpv/rikaichamp-backend/
nasir@nasir-Inspiron-15-3567:~/.config/mpv/scripts/rikai-mpv/rikaichamp-backend$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 4.03s.

**Comment by MohdNasir997** [comment]
[rikai-mpv] Starting rikai-mpv in python... 0.000
Launching node.js backend...
Connecting from Python...
Checking for leftover socket.
Removing leftover socket.
Creating server.
python <---> node.js socket connected.
Connection acknowledged.
node client connected.
QApplication: invalid style override 'adwaita' passed, ignoring it.
	Available styles: Windows, Fusion
(Paused) AV: 00:12:43 / 02:16:04 (9%) A-V:  0.000 Dropped: 19
Saving state.

Exiting... (Quit)
[front] Quitting rikai-mpv... 
[front] Finished exiting.

**Comment by MohdNasir997** [comment]
using mpvacious , I can see the subtitles , therefore , I assume , rikai is hiding the subtitles.

**Comment by MohdNasir997** [comment]
seems like a Qt problem , beacause this QApplication: invalid style override 'adwaita' passed, ignoring it.
Available styles: Windows, Fusion , doesn't appear on other outputs.

**Comment by fxmarty** [comment]
Hi @MohdNasir997 sorry for the slight delay. Yes, building upon https://github.com/oltodosel/interSubs rikai-mpv hides the mpv subtitle, and overlaps a Qt window for the subtitles + pop-up dictionary.

Yes, it could be that the issue is unrelated to rikai-mpv. Could be that the line https://github.com/fxmarty/rikai-mpv/blob/abed1e9f4475ec39d77316a3c9d34f8e1ae0abe1/subtitles_popup_graphics.py#L698 fails somehow. Are you using adwaita (for example in KDE it seems available in "global themes")? Could you try with an other theme if you still have the issue (for example on KDE, there is breeze theme)? 

I would advise also to try on of the https://github.com/pyqt/examples to see if you have the issue as well.

Maybe https://stackoverflow.com/questions/49799080/where-is-this-warning-being-raised-qapplication-invalid-style-override-passed can help as well.

**Comment by MohdNasir997** [comment]
Thanks, finally works.
