### ISSUE TITLE
Greetings

### ISSUE THREAD

**Issue by Boy19991** [fxmarty/rikai-mpv#6]
Greetings.

Rikai-mpv looks very impressive. Im still on Windows (very bad) but am planning to move to Linux soon, so maybe I can try it then.

Very interesting idea to make the popups in a movie.

I've got two questions for you.

1. It's hard to get subtitles for anime, do you have a lot of them? There was a torrent floating around a while back which had a few thousand, although many of them the timing was off, so you had to manually retime them. Pain in the ass, but I'm sure you know how valuable subtitles can be. One notable one it has was Legend of Galatic Heroes, pretty much perfectly timed.

2. I'm looking for people to help develop (or just give me guidance) a rikaikun for other languages. Are you interested? I want Hebrew, Spanish and Russian.  We could use wikitionary like Slava Translator (for Russian), but ajax request is a pain in the ass and breaks your reading flow.

Best Regards,
Nick.

**Comment by fxmarty** [comment]
Hello @Boy19991 sorry for answering that late!

1. https://kitsunekko.net/ and https://itazuraneko.neocities.org/ are your best bets, although it is doubtful those are fully legal. Some of them are fansubs though (especially from the Chinese community), so I guess this may be OK legally depending on the jurisdiction.

2. So you mean like a tool like interSubs but not for mpv, rather as an addon for Chrome/Firefox? I think it is a great project that could have a lot of impact! Not sure if it has been done already? For sure you could take inspiration from the codebase of rikaichamp, it is really well optimized.

Don't hesitate if you have any more question.

Best!
